[2022-01-15 20:15:14,129] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: stocks_dag.sql_connect_ manual__2022-01-15T20:13:09.478240+00:00 [queued]>
[2022-01-15 20:15:14,153] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: stocks_dag.sql_connect_ manual__2022-01-15T20:13:09.478240+00:00 [queued]>
[2022-01-15 20:15:14,155] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-15 20:15:14,156] {taskinstance.py:1239} INFO - Starting attempt 2 of 4
[2022-01-15 20:15:14,157] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-15 20:15:14,196] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): sql_connect_> on 2022-01-15 20:13:09.478240+00:00
[2022-01-15 20:15:14,203] {standard_task_runner.py:52} INFO - Started process 1481 to run task
[2022-01-15 20:15:14,215] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'stocks_dag', 'sql_connect_', 'manual__2022-01-15T20:13:09.478240+00:00', '--job-id', '494', '--raw', '--subdir', 'DAGS_FOLDER/stocks_dag.py', '--cfg-path', '/tmp/tmpwrgiqunk', '--error-file', '/tmp/tmptu8bbevw']
[2022-01-15 20:15:14,218] {standard_task_runner.py:77} INFO - Job 494: Subtask sql_connect_
[2022-01-15 20:15:14,324] {logging_mixin.py:109} INFO - Running <TaskInstance: stocks_dag.sql_connect_ manual__2022-01-15T20:13:09.478240+00:00 [running]> on host 241ebeaac988
[2022-01-15 20:15:14,444] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=mcgaritym@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stocks_dag
AIRFLOW_CTX_TASK_ID=sql_connect_
AIRFLOW_CTX_EXECUTION_DATE=2022-01-15T20:13:09.478240+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-15T20:13:09.478240+00:00
[2022-01-15 20:15:14,448] {logging_mixin.py:109} INFO - Parent Directory:  /opt
[2022-01-15 20:15:14,450] {logging_mixin.py:109} INFO - Current Parent Directory Files:  ['***', 'microsoft', 'mssql-tools']
[2022-01-15 20:15:14,484] {logging_mixin.py:109} INFO - Data Directory:  /opt/data
[2022-01-15 20:15:14,489] {logging_mixin.py:109} INFO - Dag Directory:  /opt/dags
[2022-01-15 20:15:14,504] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sql_connect.py", line 24, in sql_connect_1
    print('Current DAG Directory Files: ', os.listdir(dag_directory))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/dags'
[2022-01-15 20:15:14,592] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=stocks_dag, task_id=sql_connect_, execution_date=20220115T201309, start_date=20220115T201514, end_date=20220115T201514
[2022-01-15 20:15:14,633] {standard_task_runner.py:92} ERROR - Failed to execute job 494 for task sql_connect_
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sql_connect.py", line 24, in sql_connect_1
    print('Current DAG Directory Files: ', os.listdir(dag_directory))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/dags'
[2022-01-15 20:15:14,747] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-15 20:15:14,821] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
