[2022-01-11 15:18:25,275] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: stocks_dag.get_tickers_2_ manual__2022-01-11T15:18:20.929962+00:00 [queued]>
[2022-01-11 15:18:25,286] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: stocks_dag.get_tickers_2_ manual__2022-01-11T15:18:20.929962+00:00 [queued]>
[2022-01-11 15:18:25,287] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 15:18:25,288] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2022-01-11 15:18:25,289] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 15:18:25,301] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_tickers_2_> on 2022-01-11 15:18:20.929962+00:00
[2022-01-11 15:18:25,305] {standard_task_runner.py:52} INFO - Started process 102 to run task
[2022-01-11 15:18:25,309] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'stocks_dag', 'get_tickers_2_', 'manual__2022-01-11T15:18:20.929962+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/stocks_dag.py', '--cfg-path', '/tmp/tmpmxkfa7ht', '--error-file', '/tmp/tmp6013s0jr']
[2022-01-11 15:18:25,311] {standard_task_runner.py:77} INFO - Job 123: Subtask get_tickers_2_
[2022-01-11 15:18:25,365] {logging_mixin.py:109} INFO - Running <TaskInstance: stocks_dag.get_tickers_2_ manual__2022-01-11T15:18:20.929962+00:00 [running]> on host 36edd51a2216
[2022-01-11 15:18:25,409] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=mcgaritym@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stocks_dag
AIRFLOW_CTX_TASK_ID=get_tickers_2_
AIRFLOW_CTX_EXECUTION_DATE=2022-01-11T15:18:20.929962+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-11T15:18:20.929962+00:00
[2022-01-11 15:18:25,411] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_tickers_2.py", line 16, in get_tickers_2
    files = glob.glob(os.path.join(data_directory, '*nasdaq_screener*.csv'))
AttributeError: 'function' object has no attribute 'glob'
[2022-01-11 15:18:25,425] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=stocks_dag, task_id=get_tickers_2_, execution_date=20220111T151820, start_date=20220111T151825, end_date=20220111T151825
[2022-01-11 15:18:25,438] {standard_task_runner.py:92} ERROR - Failed to execute job 123 for task get_tickers_2_
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_tickers_2.py", line 16, in get_tickers_2
    files = glob.glob(os.path.join(data_directory, '*nasdaq_screener*.csv'))
AttributeError: 'function' object has no attribute 'glob'
[2022-01-11 15:18:25,484] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-11 15:18:25,517] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
